#include <unity.h>

void test_default_config_is_valid();
void test_invalid_ssid_is_rejected();
void test_store_does_not_save_invalid_wifi_credentials();
void test_json_export_redacts_password();
void test_json_import_rejects_oversized_input();
void test_device_event_payload_is_bounded();
void test_device_command_payload_is_bounded();
void test_device_event_bus_registers_fans_out_and_ticks();
void test_device_event_bus_caps_sink_count();
void test_device_event_queue_preserves_fifo_and_bounds();
void test_device_event_dispatcher_drains_queue_in_order();
void test_device_event_dispatcher_counts_dropped_events_when_full();
void test_external_device_id_uses_controller_identity_and_device_id();
void test_external_device_id_sanitizes_controller_identity();
void test_external_device_id_falls_back_for_empty_identity();
void test_device_runtime_base_begin_and_cadence_tick_state_machine();
void test_device_runtime_base_dependency_wiring();
void test_device_runtime_base_request_status_defaults();
void test_disabled_update_is_rejected();
void test_empty_image_is_rejected();
void test_oversized_image_is_rejected();
void test_valid_image_is_accepted();
void test_oversized_metadata_is_rejected();
void test_no_credentials_enters_setup_ap();
void test_credentials_start_station_connect();
void test_connection_success_keeps_setup_ap();
void test_failed_connection_retries_and_falls_back();
void test_connection_timeout_retry_resets_state_timer();
void test_wifi_readiness_requires_driver_begin_and_valid_addresses();
void test_setup_ap_readiness_requires_successful_ap_start_and_valid_ip();
void test_failed_setup_ap_start_does_not_report_setup_ap_ready();
void test_station_connect_clears_setup_ap_readiness();
void test_wifi_manager_rejects_oversized_credentials();
void test_wifi_manager_submit_credentials_saves_and_connects();
void test_wifi_manager_rejects_ble_config_when_disabled();
void test_portal_waits_for_network_stack_before_http_start();
void test_portal_dns_follows_setup_ap_readiness_without_http_restart();
void test_portal_restarts_http_only_when_network_stack_is_lost();
void test_wifi_manager_ble_config_request_starts_ble_mode();
void test_wifi_manager_rejects_portal_submit_while_ble_config_is_running();
void test_wifi_manager_ble_timeout_stops_deinitializes_and_returns();
void test_wifi_manager_ble_stop_wait_is_bounded_when_prov_end_is_missing();
void test_wifi_manager_ble_credentials_stop_deinit_save_and_connect();
void test_wifi_manager_invalid_ble_credentials_do_not_start_station_connect();
void test_arduino_ota_starts_after_wifi_connects();
void test_arduino_ota_starts_on_setup_ap_readiness();
void test_arduino_ota_stops_and_restarts_after_wifi_loss();
void test_arduino_ota_restarts_after_station_ip_changes();
void test_state_machine_stack_and_return_to_popped_state();
void test_state_machine_pause_restart_and_updated_flag();
void test_state_machine_timeout_helpers();
void test_restart_controller_requests_reboot_when_flush_succeeds();
void test_restart_controller_rejects_reboot_when_flush_fails();
void test_restart_route_build_flag_state_matches_compilation();

int main(int, char**) {
    UNITY_BEGIN();
    RUN_TEST(test_default_config_is_valid);
    RUN_TEST(test_invalid_ssid_is_rejected);
    RUN_TEST(test_store_does_not_save_invalid_wifi_credentials);
    RUN_TEST(test_json_export_redacts_password);
    RUN_TEST(test_json_import_rejects_oversized_input);
    RUN_TEST(test_device_event_payload_is_bounded);
    RUN_TEST(test_device_command_payload_is_bounded);
    RUN_TEST(test_device_event_bus_registers_fans_out_and_ticks);
    RUN_TEST(test_device_event_bus_caps_sink_count);
    RUN_TEST(test_device_event_queue_preserves_fifo_and_bounds);
    RUN_TEST(test_device_event_dispatcher_drains_queue_in_order);
    RUN_TEST(test_device_event_dispatcher_counts_dropped_events_when_full);
    RUN_TEST(test_external_device_id_uses_controller_identity_and_device_id);
    RUN_TEST(test_external_device_id_sanitizes_controller_identity);
    RUN_TEST(test_external_device_id_falls_back_for_empty_identity);
    RUN_TEST(test_device_runtime_base_begin_and_cadence_tick_state_machine);
    RUN_TEST(test_device_runtime_base_dependency_wiring);
    RUN_TEST(test_device_runtime_base_request_status_defaults);
    RUN_TEST(test_disabled_update_is_rejected);
    RUN_TEST(test_empty_image_is_rejected);
    RUN_TEST(test_oversized_image_is_rejected);
    RUN_TEST(test_valid_image_is_accepted);
    RUN_TEST(test_oversized_metadata_is_rejected);
    RUN_TEST(test_no_credentials_enters_setup_ap);
    RUN_TEST(test_credentials_start_station_connect);
    RUN_TEST(test_connection_success_keeps_setup_ap);
    RUN_TEST(test_failed_connection_retries_and_falls_back);
    RUN_TEST(test_connection_timeout_retry_resets_state_timer);
    RUN_TEST(test_wifi_readiness_requires_driver_begin_and_valid_addresses);
    RUN_TEST(test_setup_ap_readiness_requires_successful_ap_start_and_valid_ip);
    RUN_TEST(test_failed_setup_ap_start_does_not_report_setup_ap_ready);
    RUN_TEST(test_station_connect_clears_setup_ap_readiness);
    RUN_TEST(test_wifi_manager_rejects_oversized_credentials);
    RUN_TEST(test_wifi_manager_submit_credentials_saves_and_connects);
    RUN_TEST(test_wifi_manager_rejects_ble_config_when_disabled);
    RUN_TEST(test_portal_waits_for_network_stack_before_http_start);
    RUN_TEST(test_portal_dns_follows_setup_ap_readiness_without_http_restart);
    RUN_TEST(test_portal_restarts_http_only_when_network_stack_is_lost);
    RUN_TEST(test_wifi_manager_ble_config_request_starts_ble_mode);
    RUN_TEST(test_wifi_manager_rejects_portal_submit_while_ble_config_is_running);
    RUN_TEST(test_wifi_manager_ble_timeout_stops_deinitializes_and_returns);
    RUN_TEST(test_wifi_manager_ble_stop_wait_is_bounded_when_prov_end_is_missing);
    RUN_TEST(test_wifi_manager_ble_credentials_stop_deinit_save_and_connect);
    RUN_TEST(test_wifi_manager_invalid_ble_credentials_do_not_start_station_connect);
    RUN_TEST(test_arduino_ota_starts_after_wifi_connects);
    RUN_TEST(test_arduino_ota_starts_on_setup_ap_readiness);
    RUN_TEST(test_arduino_ota_stops_and_restarts_after_wifi_loss);
    RUN_TEST(test_arduino_ota_restarts_after_station_ip_changes);
    RUN_TEST(test_state_machine_stack_and_return_to_popped_state);
    RUN_TEST(test_state_machine_pause_restart_and_updated_flag);
    RUN_TEST(test_state_machine_timeout_helpers);
    RUN_TEST(test_restart_controller_requests_reboot_when_flush_succeeds);
    RUN_TEST(test_restart_controller_rejects_reboot_when_flush_fails);
    RUN_TEST(test_restart_route_build_flag_state_matches_compilation);
    return UNITY_END();
}
