#include <unity.h>

void test_default_config_is_valid();
void test_invalid_ssid_is_rejected();
void test_store_does_not_save_invalid_wifi_credentials();
void test_json_export_redacts_password();
void test_json_import_rejects_oversized_input();
void test_time_config_rejects_unknown_timezone();
void test_time_config_rejects_out_of_range_sync_interval();
void test_time_config_rejects_oversized_ntp_server();
void test_config_store_save_time_config_persists_across_reload();
void test_config_store_rejects_invalid_time_config();
void test_persistence_config_rejects_out_of_range_debounce();
void test_persistence_config_rejects_out_of_range_max_delay();
void test_persistence_config_rejects_debounce_exceeding_max_delay();
void test_config_store_save_persistence_config_persists_across_reload();
void test_config_store_rejects_invalid_persistence_config();
void test_device_event_payload_is_bounded();
void test_device_command_payload_is_bounded();
void test_device_event_bus_registers_fans_out_and_ticks();
void test_device_event_bus_caps_sink_count();
void test_device_event_queue_preserves_fifo_and_bounds();
void test_device_event_dispatcher_drains_queue_in_order();
void test_device_event_dispatcher_counts_dropped_events_when_full();
void test_external_device_id_uses_controller_identity_and_device_id();
void test_external_device_id_sanitizes_controller_identity();
void test_external_device_id_falls_back_for_empty_identity();
void test_device_runtime_base_begin_and_cadence_tick_state_machine();
void test_device_runtime_base_dependency_wiring();
void test_device_runtime_base_request_status_defaults();
void test_disabled_update_is_rejected();
void test_empty_image_is_rejected();
void test_oversized_image_is_rejected();
void test_valid_image_is_accepted();
void test_oversized_metadata_is_rejected();
void test_no_credentials_enters_setup_ap();
void test_credentials_start_station_connect();
void test_connection_success_keeps_setup_ap();
void test_failed_connection_retries_and_falls_back();
void test_connection_timeout_retry_resets_state_timer();
void test_wifi_readiness_requires_driver_begin_and_valid_addresses();
void test_setup_ap_readiness_requires_successful_ap_start_and_valid_ip();
void test_failed_setup_ap_start_does_not_report_setup_ap_ready();
void test_station_connect_clears_setup_ap_readiness();
void test_wifi_manager_rejects_oversized_credentials();
void test_wifi_manager_submit_credentials_saves_and_connects();
void test_wifi_manager_rejects_ble_config_when_disabled();
void test_portal_waits_for_network_stack_before_http_start();
void test_portal_dns_follows_setup_ap_readiness_without_http_restart();
void test_portal_restarts_http_only_when_network_stack_is_lost();
void test_wifi_manager_ble_config_request_starts_ble_mode();
void test_wifi_manager_rejects_portal_submit_while_ble_config_is_running();
void test_wifi_manager_ble_timeout_stops_deinitializes_and_returns();
void test_wifi_manager_ble_stop_wait_is_bounded_when_prov_end_is_missing();
void test_wifi_manager_ble_credentials_stop_deinit_save_and_connect();
void test_wifi_manager_invalid_ble_credentials_do_not_start_station_connect();
void test_arduino_ota_starts_after_wifi_connects();
void test_arduino_ota_starts_on_setup_ap_readiness();
void test_arduino_ota_stops_and_restarts_after_wifi_loss();
void test_arduino_ota_restarts_after_station_ip_changes();
void test_mqtt_manager_connects_after_wifi_station_ready();
void test_mqtt_manager_does_not_connect_on_setup_ap_readiness_only();
void test_mqtt_manager_stops_and_restarts_after_wifi_loss();
void test_mqtt_manager_applies_new_settings_and_reconnects();
void test_mqtt_manager_enabled_toggle_prevents_connection();
void test_state_machine_stack_and_return_to_popped_state();
void test_state_machine_pause_restart_and_updated_flag();
void test_state_machine_timeout_helpers();
void test_restart_controller_requests_reboot_when_flush_succeeds();
void test_restart_controller_rejects_reboot_when_flush_fails();
void test_restart_route_build_flag_state_matches_compilation();
void test_mqtt_route_build_flag_state_matches_compilation();
void test_date_time_epoch_zero_is_1970_01_01_thursday();
void test_date_time_known_y2k_epoch_anchor();
void test_date_time_field_round_trip_through_epoch();
void test_date_time_leap_year_day_rolls_into_march();
void test_date_time_utc_offset_arithmetic();
void test_date_time_comparison_operators_use_utc_instant();
void test_date_time_delta_addition_and_subtraction();
void test_time_delta_total_seconds_and_components();
void test_time_delta_negative_seconds_round_trip();
void test_time_zone_info_named_offset_reports_seconds();
void test_time_zone_info_auto_formats_utc_offset_name();
void test_iso8601_parses_zulu_suffix();
void test_iso8601_parses_explicit_offset();
void test_iso8601_parses_without_seconds();
void test_iso8601_rejects_malformed_input();
void test_iso8601_format_round_trip();
void test_date_time_leap_year_rules_century_boundaries();
void test_date_time_month_end_rollovers();
void test_date_time_midnight_and_end_of_day_boundaries();
void test_date_time_known_weekday_reference_y2k();
void test_date_time_equality_across_different_timezone_representations();
void test_date_time_ordering_operators_are_consistent();
void test_time_delta_zero_has_zero_components();
void test_time_delta_exact_day_multiples();
void test_time_delta_one_second_around_day_boundaries();
void test_time_delta_addition_carries_across_day_boundary();
void test_time_delta_round_trips_across_curated_boundary_values();
void test_time_zone_info_zero_offset_uses_positive_sign_not_negative_zero();
void test_time_zone_info_formats_negative_half_hour_offset();
void test_time_zone_info_formats_large_positive_offset();
void test_time_zone_info_name_truncates_safely_when_too_long();
void test_time_zone_table_has_100_entries();
void test_time_zone_table_lookup_finds_known_zone_with_dst_rule();
void test_time_zone_table_lookup_finds_fixed_offset_zone();
void test_time_zone_table_lookup_rejects_unknown_and_null();
void test_time_zone_table_matches_timezones_json();
void test_ntp_manager_waits_for_station_before_resolving();
void test_ntp_manager_syncs_after_wifi_station_ready();
void test_ntp_manager_resolve_timeout_retries_and_returns_to_waiting_for_station();
void test_ntp_manager_response_timeout_retries();
void test_ntp_manager_apply_settings_validates_and_updates_config();
void test_ntp_manager_disabled_never_syncs_even_when_station_ready();
void test_ntp_manager_manual_time_set_works_regardless_of_enabled();
void test_ntp_manager_manual_time_counts_as_authoritative_sync_and_bumps_revision();
void test_ntp_manager_seed_from_rtc_does_not_count_as_authoritative_sync();
void test_rtc_sync_coordinator_seeds_system_time_from_rtc_before_first_ntp_sync();
void test_rtc_sync_coordinator_ignores_rtc_device_not_opted_in();
void test_rtc_sync_coordinator_writes_back_after_authoritative_sync();
void test_rtc_sync_coordinator_writes_current_time_when_rtc_is_enabled_after_sync();
void test_rtc_sync_coordinator_falls_back_to_rtc_after_prolonged_ntp_outage();
void test_blob_key_segment_accepts_valid_charset();
void test_blob_key_segment_rejects_empty_dot_and_dotdot();
void test_blob_key_segment_rejects_bad_charset();
void test_blob_key_accepts_nested_valid_key();
void test_blob_key_rejects_empty_key();
void test_blob_key_rejects_leading_trailing_and_doubled_slash();
void test_blob_key_rejects_path_traversal_segment();
void test_blob_key_rejects_oversized_key_and_too_many_segments();
void test_blob_store_put_then_get_round_trips_bytes();
void test_blob_store_commit_atomically_replaces_existing_blob();
void test_blob_store_uncommitted_write_leaves_existing_blob_untouched();
void test_blob_store_remove_by_prefix_on_leaf_key_removes_only_that_file();
void test_blob_store_remove_by_prefix_on_directory_removes_recursively();
void test_blob_store_remove_by_prefix_on_missing_prefix_is_a_no_op_success();
void test_blob_store_wipe_all_clears_store_but_leaves_it_usable();
void test_blob_store_confines_all_operations_to_its_reserved_root();
void test_blob_store_refuses_write_when_free_space_guard_trips();
void test_blob_store_auto_creates_intermediate_directories_for_nested_keys();
void test_blob_store_begin_put_generated_returns_working_handle_under_prefix();
void test_blob_store_begin_put_generated_avoids_existing_key();
void test_generate_unique_blob_key_succeeds_on_first_attempt_with_no_prefix();
void test_generate_unique_blob_key_joins_prefix_with_slash();
void test_generate_unique_blob_key_retries_on_collision();
void test_generate_unique_blob_key_fails_after_exhausting_attempts();
void test_blob_store_device_cleanup_sink_removes_only_the_deleted_devices_blobs();
void test_blob_store_device_cleanup_sink_ignores_non_delete_events();
void test_blob_store_device_cleanup_sink_deleting_device_with_no_blobs_is_a_no_op();

int main(int, char**) {
    UNITY_BEGIN();
    RUN_TEST(test_default_config_is_valid);
    RUN_TEST(test_invalid_ssid_is_rejected);
    RUN_TEST(test_store_does_not_save_invalid_wifi_credentials);
    RUN_TEST(test_json_export_redacts_password);
    RUN_TEST(test_json_import_rejects_oversized_input);
    RUN_TEST(test_time_config_rejects_unknown_timezone);
    RUN_TEST(test_time_config_rejects_out_of_range_sync_interval);
    RUN_TEST(test_time_config_rejects_oversized_ntp_server);
    RUN_TEST(test_config_store_save_time_config_persists_across_reload);
    RUN_TEST(test_config_store_rejects_invalid_time_config);
    RUN_TEST(test_persistence_config_rejects_out_of_range_debounce);
    RUN_TEST(test_persistence_config_rejects_out_of_range_max_delay);
    RUN_TEST(test_persistence_config_rejects_debounce_exceeding_max_delay);
    RUN_TEST(test_config_store_save_persistence_config_persists_across_reload);
    RUN_TEST(test_config_store_rejects_invalid_persistence_config);
    RUN_TEST(test_device_event_payload_is_bounded);
    RUN_TEST(test_device_command_payload_is_bounded);
    RUN_TEST(test_device_event_bus_registers_fans_out_and_ticks);
    RUN_TEST(test_device_event_bus_caps_sink_count);
    RUN_TEST(test_device_event_queue_preserves_fifo_and_bounds);
    RUN_TEST(test_device_event_dispatcher_drains_queue_in_order);
    RUN_TEST(test_device_event_dispatcher_counts_dropped_events_when_full);
    RUN_TEST(test_external_device_id_uses_controller_identity_and_device_id);
    RUN_TEST(test_external_device_id_sanitizes_controller_identity);
    RUN_TEST(test_external_device_id_falls_back_for_empty_identity);
    RUN_TEST(test_device_runtime_base_begin_and_cadence_tick_state_machine);
    RUN_TEST(test_device_runtime_base_dependency_wiring);
    RUN_TEST(test_device_runtime_base_request_status_defaults);
    RUN_TEST(test_disabled_update_is_rejected);
    RUN_TEST(test_empty_image_is_rejected);
    RUN_TEST(test_oversized_image_is_rejected);
    RUN_TEST(test_valid_image_is_accepted);
    RUN_TEST(test_oversized_metadata_is_rejected);
    RUN_TEST(test_no_credentials_enters_setup_ap);
    RUN_TEST(test_credentials_start_station_connect);
    RUN_TEST(test_connection_success_keeps_setup_ap);
    RUN_TEST(test_failed_connection_retries_and_falls_back);
    RUN_TEST(test_connection_timeout_retry_resets_state_timer);
    RUN_TEST(test_wifi_readiness_requires_driver_begin_and_valid_addresses);
    RUN_TEST(test_setup_ap_readiness_requires_successful_ap_start_and_valid_ip);
    RUN_TEST(test_failed_setup_ap_start_does_not_report_setup_ap_ready);
    RUN_TEST(test_station_connect_clears_setup_ap_readiness);
    RUN_TEST(test_wifi_manager_rejects_oversized_credentials);
    RUN_TEST(test_wifi_manager_submit_credentials_saves_and_connects);
    RUN_TEST(test_wifi_manager_rejects_ble_config_when_disabled);
    RUN_TEST(test_portal_waits_for_network_stack_before_http_start);
    RUN_TEST(test_portal_dns_follows_setup_ap_readiness_without_http_restart);
    RUN_TEST(test_portal_restarts_http_only_when_network_stack_is_lost);
    RUN_TEST(test_wifi_manager_ble_config_request_starts_ble_mode);
    RUN_TEST(test_wifi_manager_rejects_portal_submit_while_ble_config_is_running);
    RUN_TEST(test_wifi_manager_ble_timeout_stops_deinitializes_and_returns);
    RUN_TEST(test_wifi_manager_ble_stop_wait_is_bounded_when_prov_end_is_missing);
    RUN_TEST(test_wifi_manager_ble_credentials_stop_deinit_save_and_connect);
    RUN_TEST(test_wifi_manager_invalid_ble_credentials_do_not_start_station_connect);
    RUN_TEST(test_arduino_ota_starts_after_wifi_connects);
    RUN_TEST(test_arduino_ota_starts_on_setup_ap_readiness);
    RUN_TEST(test_arduino_ota_stops_and_restarts_after_wifi_loss);
    RUN_TEST(test_arduino_ota_restarts_after_station_ip_changes);
    RUN_TEST(test_mqtt_manager_connects_after_wifi_station_ready);
    RUN_TEST(test_mqtt_manager_does_not_connect_on_setup_ap_readiness_only);
    RUN_TEST(test_mqtt_manager_stops_and_restarts_after_wifi_loss);
    RUN_TEST(test_mqtt_manager_applies_new_settings_and_reconnects);
    RUN_TEST(test_mqtt_manager_enabled_toggle_prevents_connection);
    RUN_TEST(test_state_machine_stack_and_return_to_popped_state);
    RUN_TEST(test_state_machine_pause_restart_and_updated_flag);
    RUN_TEST(test_state_machine_timeout_helpers);
    RUN_TEST(test_restart_controller_requests_reboot_when_flush_succeeds);
    RUN_TEST(test_restart_controller_rejects_reboot_when_flush_fails);
    RUN_TEST(test_restart_route_build_flag_state_matches_compilation);
    RUN_TEST(test_mqtt_route_build_flag_state_matches_compilation);
    RUN_TEST(test_date_time_epoch_zero_is_1970_01_01_thursday);
    RUN_TEST(test_date_time_known_y2k_epoch_anchor);
    RUN_TEST(test_date_time_field_round_trip_through_epoch);
    RUN_TEST(test_date_time_leap_year_day_rolls_into_march);
    RUN_TEST(test_date_time_utc_offset_arithmetic);
    RUN_TEST(test_date_time_comparison_operators_use_utc_instant);
    RUN_TEST(test_date_time_delta_addition_and_subtraction);
    RUN_TEST(test_time_delta_total_seconds_and_components);
    RUN_TEST(test_time_delta_negative_seconds_round_trip);
    RUN_TEST(test_time_zone_info_named_offset_reports_seconds);
    RUN_TEST(test_time_zone_info_auto_formats_utc_offset_name);
    RUN_TEST(test_iso8601_parses_zulu_suffix);
    RUN_TEST(test_iso8601_parses_explicit_offset);
    RUN_TEST(test_iso8601_parses_without_seconds);
    RUN_TEST(test_iso8601_rejects_malformed_input);
    RUN_TEST(test_iso8601_format_round_trip);
    RUN_TEST(test_date_time_leap_year_rules_century_boundaries);
    RUN_TEST(test_date_time_month_end_rollovers);
    RUN_TEST(test_date_time_midnight_and_end_of_day_boundaries);
    RUN_TEST(test_date_time_known_weekday_reference_y2k);
    RUN_TEST(test_date_time_equality_across_different_timezone_representations);
    RUN_TEST(test_date_time_ordering_operators_are_consistent);
    RUN_TEST(test_time_delta_zero_has_zero_components);
    RUN_TEST(test_time_delta_exact_day_multiples);
    RUN_TEST(test_time_delta_one_second_around_day_boundaries);
    RUN_TEST(test_time_delta_addition_carries_across_day_boundary);
    RUN_TEST(test_time_delta_round_trips_across_curated_boundary_values);
    RUN_TEST(test_time_zone_info_zero_offset_uses_positive_sign_not_negative_zero);
    RUN_TEST(test_time_zone_info_formats_negative_half_hour_offset);
    RUN_TEST(test_time_zone_info_formats_large_positive_offset);
    RUN_TEST(test_time_zone_info_name_truncates_safely_when_too_long);
    RUN_TEST(test_time_zone_table_has_100_entries);
    RUN_TEST(test_time_zone_table_lookup_finds_known_zone_with_dst_rule);
    RUN_TEST(test_time_zone_table_lookup_finds_fixed_offset_zone);
    RUN_TEST(test_time_zone_table_lookup_rejects_unknown_and_null);
    RUN_TEST(test_time_zone_table_matches_timezones_json);
    RUN_TEST(test_ntp_manager_waits_for_station_before_resolving);
    RUN_TEST(test_ntp_manager_syncs_after_wifi_station_ready);
    RUN_TEST(test_ntp_manager_resolve_timeout_retries_and_returns_to_waiting_for_station);
    RUN_TEST(test_ntp_manager_response_timeout_retries);
    RUN_TEST(test_ntp_manager_apply_settings_validates_and_updates_config);
    RUN_TEST(test_ntp_manager_disabled_never_syncs_even_when_station_ready);
    RUN_TEST(test_ntp_manager_manual_time_set_works_regardless_of_enabled);
    RUN_TEST(test_ntp_manager_manual_time_counts_as_authoritative_sync_and_bumps_revision);
    RUN_TEST(test_ntp_manager_seed_from_rtc_does_not_count_as_authoritative_sync);
    RUN_TEST(test_rtc_sync_coordinator_seeds_system_time_from_rtc_before_first_ntp_sync);
    RUN_TEST(test_rtc_sync_coordinator_ignores_rtc_device_not_opted_in);
    RUN_TEST(test_rtc_sync_coordinator_writes_back_after_authoritative_sync);
    RUN_TEST(test_rtc_sync_coordinator_writes_current_time_when_rtc_is_enabled_after_sync);
    RUN_TEST(test_rtc_sync_coordinator_falls_back_to_rtc_after_prolonged_ntp_outage);
    RUN_TEST(test_blob_key_segment_accepts_valid_charset);
    RUN_TEST(test_blob_key_segment_rejects_empty_dot_and_dotdot);
    RUN_TEST(test_blob_key_segment_rejects_bad_charset);
    RUN_TEST(test_blob_key_accepts_nested_valid_key);
    RUN_TEST(test_blob_key_rejects_empty_key);
    RUN_TEST(test_blob_key_rejects_leading_trailing_and_doubled_slash);
    RUN_TEST(test_blob_key_rejects_path_traversal_segment);
    RUN_TEST(test_blob_key_rejects_oversized_key_and_too_many_segments);
    RUN_TEST(test_blob_store_put_then_get_round_trips_bytes);
    RUN_TEST(test_blob_store_commit_atomically_replaces_existing_blob);
    RUN_TEST(test_blob_store_uncommitted_write_leaves_existing_blob_untouched);
    RUN_TEST(test_blob_store_remove_by_prefix_on_leaf_key_removes_only_that_file);
    RUN_TEST(test_blob_store_remove_by_prefix_on_directory_removes_recursively);
    RUN_TEST(test_blob_store_remove_by_prefix_on_missing_prefix_is_a_no_op_success);
    RUN_TEST(test_blob_store_wipe_all_clears_store_but_leaves_it_usable);
    RUN_TEST(test_blob_store_confines_all_operations_to_its_reserved_root);
    RUN_TEST(test_blob_store_refuses_write_when_free_space_guard_trips);
    RUN_TEST(test_blob_store_auto_creates_intermediate_directories_for_nested_keys);
    RUN_TEST(test_blob_store_begin_put_generated_returns_working_handle_under_prefix);
    RUN_TEST(test_blob_store_begin_put_generated_avoids_existing_key);
    RUN_TEST(test_generate_unique_blob_key_succeeds_on_first_attempt_with_no_prefix);
    RUN_TEST(test_generate_unique_blob_key_joins_prefix_with_slash);
    RUN_TEST(test_generate_unique_blob_key_retries_on_collision);
    RUN_TEST(test_generate_unique_blob_key_fails_after_exhausting_attempts);
    RUN_TEST(test_blob_store_device_cleanup_sink_removes_only_the_deleted_devices_blobs);
    RUN_TEST(test_blob_store_device_cleanup_sink_ignores_non_delete_events);
    RUN_TEST(test_blob_store_device_cleanup_sink_deleting_device_with_no_blobs_is_a_no_op);
    return UNITY_END();
}
