#!/usr/bin/env bash
# Flashes the firmware via standalone esptool (no Python, no browser needed).
# "default" is the recommended build (no BLE provisioning); "ble" adds BLE WiFi
# provisioning and its setup-button GPIO reservation, at the cost of flash/RAM.
# CHIP is one of esp32 (default), esp32s2, esp32s3, esp32c3, esp32c6 -- match the
# board you actually have; "ble" only exists for esp32/esp32s3/esp32c3.
# Download the esptool binary for your OS and place it next to this script:
#   https://github.com/espressif/esptool/releases
# (the file is named esptool or esptool-macos/esptool-linux -- rename it to esptool)
#
# Usage: ./flash.sh [default|ble] [CHIP] [PORT] [all|bootloader|partitions|firmware|littlefs]
# The target can be passed without a port, for example: ./flash.sh littlefs
set -euo pipefail
cd "$(dirname "$0")"

VARIANT="default"
VARIANT_DIR="."
if [ "${1-}" = "default" ] || [ "${1-}" = "ble" ]; then
  VARIANT="$1"
  shift
fi
if [ "$VARIANT" = "ble" ]; then
  VARIANT_DIR="./ble"
fi

CHIP="esp32"
case "${1-}" in
  esp32|esp32s2|esp32s3|esp32c3|esp32c6) CHIP="$1"; shift ;;
esac
BUNDLE_DIR="$VARIANT_DIR/$CHIP"

if [ ! -f "$BUNDLE_DIR/flash-layout.env" ]; then
  echo "$BUNDLE_DIR/flash-layout.env not found."
  exit 1
fi
# Generated by scripts/collect_webflash.py from my_partitions.csv.
. "$BUNDLE_DIR/flash-layout.env"

ESPTOOL="./esptool"
if [ ! -x "$ESPTOOL" ]; then
  if command -v esptool >/dev/null 2>&1; then
    ESPTOOL="esptool"
  else
    echo "esptool not found. Download the binary for your OS:"
    echo "  https://github.com/espressif/esptool/releases"
    echo "and place it next to flash.sh as 'esptool' (chmod +x esptool)."
    exit 1
  fi
fi

TARGET="all"
PORT=""
case "${1-}" in
  all|bootloader|partitions|firmware|littlefs) TARGET="$1" ;;
  "") ;;
  *) PORT="$1" ;;
esac
if [ "${2-}" != "" ]; then
  TARGET="$2"
fi

case "$TARGET" in
  all)
    FLASH_FILE="$MERGED_FILE"
    FLASH_OFFSET="$MERGED_OFFSET"
    echo "WARNING: the combined image erases devdata; use a selective target to preserve it."
    ;;
  bootloader) FLASH_FILE="$BOOTLOADER_FILE"; FLASH_OFFSET="$BOOTLOADER_OFFSET" ;;
  partitions) FLASH_FILE="$PARTITIONS_FILE"; FLASH_OFFSET="$PARTITIONS_OFFSET" ;;
  firmware) FLASH_FILE="$FIRMWARE_FILE"; FLASH_OFFSET="$FIRMWARE_OFFSET" ;;
  littlefs) FLASH_FILE="$LITTLEFS_FILE"; FLASH_OFFSET="$LITTLEFS_OFFSET" ;;
  *) echo "Unknown target: $TARGET"; exit 2 ;;
esac
FLASH_FILE="$BUNDLE_DIR/$FLASH_FILE"

PORT_ARGS=()
if [ "$PORT" != "" ]; then
  PORT_ARGS=(--port "$PORT")
fi

"$ESPTOOL" --chip "$CHIP" --baud 921600 "${PORT_ARGS[@]}" write_flash -z \
  --flash_mode keep --flash_freq keep --flash_size detect \
  "$FLASH_OFFSET" "$FLASH_FILE"
