import 'vuetify/styles'

import { createVuetify } from 'vuetify'
import {
  VApp,
  VAppBar,
  VAppBarTitle,
  VBtn,
  VBtnToggle,
  VAlert,
  VAutocomplete,
  VCard,
  VCardActions,
  VCardItem,
  VCardText,
  VCardTitle,
  VChip,
  VCol,
  VContainer,
  VDivider,
  VDialog,
  VCheckbox,
  VFileInput,
  VForm,
  VMain,
  VIcon,
  VProgressCircular,
  VNavigationDrawer,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelTitle,
  VExpansionPanelText,
  VList,
  VListItem,
  VListItemSubtitle,
  VListItemTitle,
  VRow,
  VSpacer,
  VSelect,
  VSheet,
  VSlider,
  VSnackbar,
  VSnackbarQueue,
  VSwitch,
  VTextField,
  VTextarea,
  VToolbar,
  VToolbarTitle,
  VTooltip,
  VTable,
  VTab,
  VTabs,
  VTabsWindow,
  VTabsWindowItem,
} from 'vuetify/components'

import { portalDefaults, portalIconAliases, portalIconSet, portalThemes } from '@/theme/portal-ui'

export function createAppVuetify() {
  return createVuetify({
    components: {
      VApp,
      VAppBar,
      VAppBarTitle,
      VBtn,
      VBtnToggle,
      VAlert,
      VAutocomplete,
      VCard,
      VCardActions,
      VCardItem,
      VCardText,
      VCardTitle,
      VChip,
      VCol,
      VContainer,
      VDivider,
      VDialog,
      VCheckbox,
      VFileInput,
      VForm,
      VMain,
      VIcon,
      VProgressCircular,
      VNavigationDrawer,
      VExpansionPanels,
      VExpansionPanel,
      VExpansionPanelTitle,
      VExpansionPanelText,
      VList,
      VListItem,
      VListItemSubtitle,
      VListItemTitle,
      VRow,
      VSpacer,
      VSelect,
      VSheet,
      VSlider,
      VSnackbar,
  VSnackbarQueue,
      VSwitch,
      VTextField,
      VTextarea,
      VToolbar,
      VToolbarTitle,
      VTooltip,
      VTable,
      VTab,
      VTabs,
      VTabsWindow,
      VTabsWindowItem,
    },
    defaults: portalDefaults,
    icons: {
      defaultSet: 'portal',
      aliases: {
        ...portalIconAliases,
      },
      sets: {
        portal: portalIconSet,
      },
    },
    theme: {
      defaultTheme: 'appLight',
      themes: portalThemes,
    },
  })
}
