#pragma once

// GENERATED by tools/devicegen/generate_boards.py for chip: esp32
// DO NOT EDIT BY HAND -- see docs/pin-configuration-conventions.md
//
// One table per compiled chip, not per board model: pin validity (can this GPIO be
// ADC1/output/etc) is a fact about the chip's silicon, shared by every board built on
// it. Which of the chip's pins a specific board actually breaks out on its header is a
// UI-picker concern handled by the SPA's full board catalog, not by firmware validation.

#include <cstddef>
#include <cstdint>
#include <cstring>

namespace ewfm {

constexpr const char* kChipId = "esp32";

constexpr uint8_t kPinRoleOutput = 1U << 0U;
constexpr uint8_t kPinRoleInput = 1U << 1U;
constexpr uint8_t kPinRoleAdc1 = 1U << 2U;
constexpr uint8_t kPinRoleAdc2 = 1U << 3U;
constexpr uint8_t kPinRoleStrapping = 1U << 4U;
constexpr uint8_t kPinRoleReservedFlash = 1U << 5U;

struct BoardPinCapability {
    uint8_t gpio;
    uint8_t roleMask;
};

constexpr BoardPinCapability kChipPins[] = {
    {0U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2 | kPinRoleStrapping},
    {1U, kPinRoleOutput | kPinRoleInput},
    {2U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2 | kPinRoleStrapping},
    {3U, kPinRoleOutput | kPinRoleInput},
    {4U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2},
    {5U, kPinRoleOutput | kPinRoleInput | kPinRoleStrapping},
    {6U, kPinRoleReservedFlash},
    {7U, kPinRoleReservedFlash},
    {8U, kPinRoleReservedFlash},
    {9U, kPinRoleReservedFlash},
    {10U, kPinRoleReservedFlash},
    {11U, kPinRoleReservedFlash},
    {12U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2 | kPinRoleStrapping},
    {13U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2},
    {14U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2},
    {15U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2 | kPinRoleStrapping},
    {16U, kPinRoleOutput | kPinRoleInput},
    {17U, kPinRoleOutput | kPinRoleInput},
    {18U, kPinRoleOutput | kPinRoleInput},
    {19U, kPinRoleOutput | kPinRoleInput},
    {21U, kPinRoleOutput | kPinRoleInput},
    {22U, kPinRoleOutput | kPinRoleInput},
    {23U, kPinRoleOutput | kPinRoleInput},
    {25U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2},
    {26U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2},
    {27U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc2},
    {32U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc1},
    {33U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc1},
    {34U, kPinRoleInput | kPinRoleAdc1},
    {35U, kPinRoleInput | kPinRoleAdc1},
    {36U, kPinRoleInput | kPinRoleAdc1},
    {37U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc1},
    {38U, kPinRoleOutput | kPinRoleInput | kPinRoleAdc1},
    {39U, kPinRoleInput | kPinRoleAdc1},
};

constexpr size_t kChipPinCount = sizeof(kChipPins) / sizeof(kChipPins[0]);

inline bool boardPinHasRole(uint8_t gpio, uint8_t roleMask) {
    for (size_t i = 0; i < kChipPinCount; ++i) {
        if (kChipPins[i].gpio == gpio) {
            return (kChipPins[i].roleMask & roleMask) == roleMask;
        }
    }
    return false;
}

// Short model-id strings only (matches BoardDefinition.boardId in the SPA's full
// catalog) -- lets the firmware report which board models it recognizes for its own
// chip (e.g. over the system status API) without carrying any of the per-board label/
// note/exposed-pin detail, which stays SPA-only by design (see file header comment).
constexpr const char* kSupportedBoardIds[] = {"d1-mini32", "esp32-cam",    "esp32-devkit-v1", "heltec-wifi-kit-32", "huzzah32-feather",
                                              "lolin32",   "lolin32-lite", "nodemcu-32s",     "ttgo-t-display",     "wt32-eth01"};
constexpr size_t kSupportedBoardIdCount = sizeof(kSupportedBoardIds) / sizeof(kSupportedBoardIds[0]);

// Enum, not a string, is what actually gets persisted (DeviceConfig.boardModel, 1 byte in
// NVS) -- compiler-checked, no risk of a garbage board id ending up in storage. The
// string form only exists at the REST boundary, via BoardModelFromString/Name below.
// Same shape as gpioInputPullModeFromString/Name (BinarySensorDeviceConfig.cpp).
enum class BoardModel : uint8_t {
    D1Mini32 = 0U,
    Esp32Cam = 1U,
    Esp32DevkitV1 = 2U,
    HeltecWifiKit32 = 3U,
    Huzzah32Feather = 4U,
    Lolin32 = 5U,
    Lolin32Lite = 6U,
    Nodemcu32s = 7U,
    TtgoTDisplay = 8U,
    Wt32Eth01 = 9U,
};

constexpr BoardModel kDefaultBoardModel = BoardModel::Nodemcu32s;

inline bool boardModelFromString(const char* value, BoardModel& out) {
    if (value == nullptr) {
        return false;
    }
    for (size_t i = 0; i < kSupportedBoardIdCount; ++i) {
        if (std::strcmp(value, kSupportedBoardIds[i]) == 0) {
            out = static_cast<BoardModel>(i);
            return true;
        }
    }
    return false;
}

inline const char* boardModelName(BoardModel model) {
    const size_t index = static_cast<size_t>(model);
    return index < kSupportedBoardIdCount ? kSupportedBoardIds[index] : "";
}

} // namespace ewfm
